WHEEL := magen_statistics_service-1.0a1-py3-none-any.whl
PACKAGE_NAME = magen_statistics_service
SPHINX_DIR=docs

DOC_PACKAGES = magen_statistics_api magen_statistics_server tests

include ../common.mk
