wheel_version := $(shell python3 -c 'import __init__ as version; print(version.__version__)')
PACKAGE_NAME = magen_logger
WHEEL := $(PACKAGE_NAME)-$(wheel_version)-py3-none-any.whl

include ../common.mk
