wheel_version := $(shell python3 -c 'import __init__ as version; print(version.__version__)')
WHEEL := magen_id_client-$(wheel_version)-py3-none-any.whl
PACKAGE_NAME = magen_id_client
SPHINX_DIR = docs

DOC_PACKAGES = magen_id_client_apis tests

include ../common.mk
