wheel_version := $(shell python3 -c 'import __init__ as version; print(version.__version__)')
WHEEL := magen_datastore-$(wheel_version)-py3-none-any.whl
PACKAGE_NAME = magen_datastore

include ../common.mk
