wheel_version := $(shell python3 -c 'import __init__ as version; print(version.__version__)')
WHEEL := magen_gmail_client-$(wheel_version)-py3-none-any.whl
PACKAGE_NAME = magen_gmail_client
SPHINX_DIR = docs

DOC_PACKAGES = magen_gmail_client_api

include ../common.mk
