wheel_version := $(shell python3 -c 'import __init__ as version; print(version.__version__)')
WHEEL := magen_utils-$(wheel_version)-py3-none-any.whl
PACKAGE_NAME = magen_utils
SPHINX_DIR = docs

DOC_PACKAGES = magen_utils_apis

include ../common.mk
